name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
    - name: build and deploy
      if: success() && github.ref == 'refs/heads/master'
      run: |
        git config user.email "${{ secrets.GIT_EMAIL }}"
        git config user.name "${{ secrets.GIT_NAME }}"
        npm run deploy --repo "https\://nodeschool\:${{ secrets.GITHUB_TOKEN }}@github.com/nodeschool/lima.git"
